-- Enable required PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create vector store table for document embeddings
CREATE TABLE IF NOT EXISTS vector_store (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    content text,
    metadata json,
    embedding vector(1024)  -- Ollama nomic-embed-text dimension is 1024
);

-- Create HNSW index for efficient similarity search
CREATE INDEX IF NOT EXISTS vector_store_embedding_idx 
ON vector_store USING HNSW (embedding vector_cosine_ops);

-- Chat memory tables will be created automatically by Spring AI JDBC repository
-- But we ensure the extensions are available

-- Create a comment for documentation
COMMENT ON TABLE vector_store IS 'Stores document embeddings for semantic search using pgvector';
COMMENT ON COLUMN vector_store.embedding IS 'Vector embedding generated by Ollama nomic-embed-text model (1024 dimensions)';

